###Register

POST http://127.0.0.1:8000/api/register/ 
Content-Type: application/json

{
    "name": "muhovo", 
    "email": "muhovo@cu.com", 
    "password": "123Qw1245", 
    "Mobile_No": "0708419386"
}

###login

Send request 
POST http://127.0.0.1:8000/api/login/ 
Content-Type: application/json

{
    "email": "muhovo@cu.com", 
    "password": "123Qw1245",
}

###Users

# Send request 
# GET http://127.0.0.1:8000/auth/users/